export function buildModelServiceApi({
  modelConfigFiles,
  currentConfigFile,
  modelList,
  globalOpacity,
  modelPosition,
  modelTransform,
  modelLoadStatus,
  loading,
  selectedModel,
  undergroundViewEnabled,
  globeFrontFaceAlpha,
  globeBackFaceAlpha,
  onConfigChange,
  interaction,
  fitToModel,
  resetView,
  resetModel,
  setUndergroundViewEnabled,
  updateGlobeTranslucency,
  enterUndergroundView,
  updatePosition,
  updateTransform,
  updateModelId,
  reloadCurrentConfig,
  reloadCurrentModelWithLodConfig,
  saveModelConfig,
  initModel,
  destroyModel,
  lodConfig,
  getLodStats,
  updateLodConfig,
  applyLodPreset,
  resetLodConfig,
  defaultLodConfig,
  lodRuntime,
  adaptiveLoad,
  lodVisualizationState,
  applyLodVisualizationMode,
  tilesetRef,
  getOriginalModelMatrix
}) {
  return {
    modelConfigFiles,
    currentConfigFile,
    modelList,
    globalOpacity,
    modelPosition,
    modelTransform,
    modelLoadStatus,
    loading,
    selectedModel,
    undergroundViewEnabled,
    globeFrontFaceAlpha,
    globeBackFaceAlpha,
    onConfigChange,
    toggleModelVisibility: model => interaction.toggleModelVisibility(model),
    updateModelOpacity: model => interaction.updateModelOpacity(model),
    updateGlobalOpacity: newOpacity => {
      globalOpacity.value = Number(newOpacity)
      interaction.updateGlobalOpacity(globalOpacity.value, modelList)
    },
    resetAllOpacity: () => interaction.resetAllOpacity(modelList),
    showAllModels: () => interaction.showAllModels(modelList),
    hideAllModels: () => interaction.hideAllModels(modelList),
    fitToModel,
    fitToModels: fitToModel,
    resetView,
    resetModel,
    setUndergroundViewEnabled,
    updateGlobeTranslucency,
    enterUndergroundView,
    updatePosition,
    updateTransform,
    syncModelInfo: model => {
      selectedModel.value = model
    },
    highlightModel: model => interaction.highlightModel(model),
    showModelProperties: model => {
      selectedModel.value = model
    },
    showOnlyModel: model => interaction.showOnlyModel(model, modelList),
    updateModelId,
    reloadCurrentConfig,
    reloadCurrentModelWithLodConfig,
    saveModelConfig,
    disableSelection: () => interaction.disableSelection(),
    enableSelection: () => interaction.enableSelection(),
    initModel,
    destroyModel,
    lodConfig,
    getLodStats,
    updateLodConfig,
    applyLodPreset,
    resetLodConfig,
    DEFAULT_LOD_CONFIG: defaultLodConfig,
    lodRuntime,
    adaptiveLoadState: adaptiveLoad.adaptiveLoadState,
    lodVisualizationState,
    applyLodVisualizationMode,
    tilesetRef,
    tileset: tilesetRef,
    modelClickHandler: () => interaction.modelClickHandler(),
    getOriginalModelMatrix,
    fps: adaptiveLoad.fps,
    startGlobalFpsMonitoring: () =>
      adaptiveLoad.startGlobalFpsMonitoring(tilesetRef, lodConfig, lodRuntime),
    stopGlobalFpsMonitoring: () => adaptiveLoad.stopGlobalFpsMonitoring(tilesetRef, lodConfig)
  }
}
